import {
  ReactIcon, NextJsIcon, NodeJsIcon, ExpressIcon, TypeScriptIcon, JavaScriptIcon,
  GoIcon, PostgreSQLIcon, MySQLIcon, MongoDBIcon, RedisIcon, PrismaIcon, DrizzleIcon,
  DockerIcon, GitIcon, GitHubSkillIcon, TurboRepoIcon, CICDIcon, WebSocketIcon,
  JavaIcon, JenkinsIcon, KafkaIcon, AWSIcon, SQLIcon, DSAIcon, OOPsIcon,
  RestAPIIcon, MonitorIcon, LogIcon,
  TailwindIcon, ZodIcon, JestIcon, SeleniumIcon, JiraIcon, VercelIcon, LinuxIcon, NginxIcon, HtmlCssIcon,
  ReduxIcon, ZustandIcon, JwtIcon, OAuthIcon, ClerkIcon, PostmanIcon, SwaggerIcon, EslintPrettierIcon,
  S3Icon, EC2Icon, CloudflareIcon, BashIcon, NpmIcon, AgileIcon, NotionIcon, GoogleApisIcon,
} from '@/components/icons/skills';
import { GithubIcon, LinkedInIcon, MailIcon, LeetCodeIcon } from '@/components/icons';

export const skillIconMap: Record<string, React.ReactNode> = {
  'React': <ReactIcon />,
  'React.js': <ReactIcon />,
  'Next.js': <NextJsIcon />,
  'Node.js': <NodeJsIcon />,
  'Express.js': <ExpressIcon />,
  'TypeScript': <TypeScriptIcon />,
  'JavaScript': <JavaScriptIcon />,
  'Go': <GoIcon />,
  'PostgreSQL': <PostgreSQLIcon />,
  'MySQL': <MySQLIcon />,
  'MongoDB': <MongoDBIcon />,
  'Redis': <RedisIcon />,
  'Prisma': <PrismaIcon />,
  'Drizzle': <DrizzleIcon />,
  'Drizzle ORM': <DrizzleIcon />,
  'Docker': <DockerIcon />,
  'Git': <GitIcon />,
  'GitHub': <GitHubSkillIcon />,
  'GitHub Actions': <GitHubSkillIcon />,
  'Turborepo': <TurboRepoIcon />,
  'CI/CD': <CICDIcon />,
  'WebSocket': <WebSocketIcon />,
  'WebSockets': <WebSocketIcon />,
  'Java': <JavaIcon />,
  'Jenkins': <JenkinsIcon />,
  'Kafka': <KafkaIcon />,
  'AWS': <AWSIcon />,
  'SQL': <SQLIcon />,
  'DSA': <DSAIcon />,
  'OOPs': <OOPsIcon />,
  'REST APIs': <RestAPIIcon />,
  'Monitoring': <MonitorIcon />,
  'Logging': <LogIcon />,
  'Tailwind CSS': <TailwindIcon />,
  'HTML/CSS': <HtmlCssIcon />,
  'Zod': <ZodIcon />,
  'Jest': <JestIcon />,
  'Selenium': <SeleniumIcon />,
  'Jira': <JiraIcon />,
  'Vercel': <VercelIcon />,
  'Linux': <LinuxIcon />,
  'Nginx': <NginxIcon />,
  'Redux': <ReduxIcon />,
  'Zustand': <ZustandIcon />,
  'JWT': <JwtIcon />,
  'OAuth': <OAuthIcon />,
  'Clerk': <ClerkIcon />,
  'Postman': <PostmanIcon />,
  'Swagger': <SwaggerIcon />,
  'ESLint': <EslintPrettierIcon />,
  'AWS S3': <S3Icon />,
  'AWS EC2': <EC2Icon />,
  'Cloudflare': <CloudflareIcon />,
  'Bash': <BashIcon />,
  'npm/yarn': <NpmIcon />,
  'Agile': <AgileIcon />,
  'Notion': <NotionIcon />,
  'Google APIs': <GoogleApisIcon />,
};

export const socialIconMap: Record<string, (props: { className?: string }) => React.ReactNode> = {
  linkedin: (props) => <LinkedInIcon {...props} />,
  github: (props) => <GithubIcon {...props} />,
  leetcode: (props) => <LeetCodeIcon {...props} />,
  email: (props) => <MailIcon {...props} />,
};
